apiVersion: v1
kind: Template
metadata:
  name: wfswarm-istio-security-greeting-service
  annotations:
    iconClass: icon-jboss
    tags: wildfly-swarm, security, java, microservice
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: The Istio Security Mission shows Mutual TLS and ACL on Istio
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wfswarm-istio-security-greeting
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-wfswarm-istio-security-greeting
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wfswarm-istio-security-greeting
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: wfswarm-istio-security-greeting:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-wfswarm-istio-security-greeting:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: ARTIFACT_COPY_ARGS
          value: "*-swarm.jar"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: wfswarm-istio-security-greeting
    name: sa-greeting
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wfswarm-istio-security-greeting
      group: io.openshift.booster
      expose: "true"
    name: wfswarm-istio-security-greeting
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wfswarm-istio-security-greeting
      group: io.openshift.booster
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: wfswarm-istio-security-greeting
      group: io.openshift.booster
    name: wfswarm-istio-security-greeting
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: wfswarm-istio-security-greeting
      group: io.openshift.booster
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
        labels:
          app: wfswarm-istio-security-greeting
          group: io.openshift.booster
      spec:
        serviceAccountName: sa-greeting
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: wfswarm-istio-security-greeting:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          name: wildfly-swarm
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wildfly-swarm
        from:
          kind: ImageStreamTag
          name: wfswarm-istio-security-greeting:latest
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      app: wfswarm-istio-security-greeting
      group: io.openshift.booster
    name: wfswarm-istio-security-greeting
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: wfswarm-istio-security-greeting
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: gateway
    annotations:
      kubernetes.io/ingress.class: istio
  spec:
    rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: wfswarm-istio-security-greeting
            servicePort: 8080
        - path: /api/greeting
          backend:
            serviceName: wfswarm-istio-security-greeting
            servicePort: 8080